version: "3.8"
services:
  xwblog:
    image: node:14.17.0
    restart: always
    volumes: 
      - ./:/home/node
    # 修改加密规则为“mysql_native_password”
    command:
      - /bin/bash
      - -c
      - |
        cd /home/node
        npm install
        npm run build
        npm run start
    ports:
      - 8080:4001
    networks: 
      - mysql0
networks: 
  mysql0:
    external: true